### ISSUE TITLE
Species checklists generated from Regions are blank

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/regions#102]
Species checklist downloads are blank. This is only when produced via the Regions tool (either from a direct download or following through to view records in the Biocache, then download). 

Species checklist downloads are not blank when produced from a Biocache query directly. 

Reported by user, replicated by KM and TH - ticket #[180399](https://support.ehelp.edu.au/a/tickets/180399)

**Comment by adam-collins** [comment]
@kylie-m Can I please get an example. I tested https://regions.ala.org.au/Bush%20Heritage%20Reserves/Beringa#group=ALL_SPECIES&subgroup=&guid=&from=1850&to=2023&tab=speciesTab&fq= and the checklist download was not blank.

**Comment by kylie-m** [comment]
No worries @adam-collins, here's the primary example - 

[https://regions.ala.org.au/Local%20government/MORETON%2520BAY%2520REGIONAL#group=Reptiles&subgroup=&guid=&from=1850&to=2023&tab=speciesTab&fq=species_subgroup%3A(%22Lizards,%20Snakes%22%20OR%20%22Tortoises,%20Turtles,%20Terrapins%22)](https://regions.ala.org.au/Local%20government/MORETON%2520BAY%2520REGIONAL#group=Reptiles&subgroup=&guid=&from=1850&to=2023&tab=speciesTab&fq=species_subgroup%3A(%22Lizards,%20Snakes%22%20OR%20%22Tortoises,%20Turtles,%20Terrapins%22))

and a couple more:

[Moreton Bay regional - mammals](https://regions.ala.org.au/Local%20government/MORETON%2520BAY%2520REGIONAL#group=Mammals&subgroup=&guid=&from=1850&to=2023&tab=speciesTab&fq=species_subgroup%3A(%22Carnivorous%20Marsupials%22%20OR%20%22Herbivorous%20Marsupials%22%20OR%20%22Bandicoots,%20Bilbies%22%20OR%20%22Monotremes%22%20OR%20%22Even-toed%20hoofed%22%20OR%20%22Carnivores%22%20OR%20%22Dolphins,%20Porpoises,%20Whales%22%20OR%20%22Bats%22%20OR%20%22Hares,%20Pikas,%20Rabbits%22%20OR%20%22Rodents%22%20OR%20%22Dugongs,%20Manatees,%20Sea%20Cows%22))

[NT - reptiles](https://regions.ala.org.au/States%20and%20territories/NORTHERN%2520TERRITORY#group=Reptiles&subgroup=&guid=&from=1850&to=2023&tab=speciesTab&fq=species_subgroup%3A(%22Crocodiles%22%20OR%20%22Lizards,%20Snakes%22%20OR%20%22Tortoises,%20Turtles,%20Terrapins%22))

[ACT - fish](https://regions.ala.org.au/States%20and%20territories/AUSTRALIAN%2520CAPITAL%2520TERRITORY#group=Fish&subgroup=&guid=&from=1850&to=2023&tab=speciesTab&fq=species_subgroup%3A(%22Killifishes%22%20OR%20%22Perch-like%20Fishes%22%20OR%20%22Scorpion%20Fishes,%20Sculpins%22%20OR%20%22Marine%20ray-finned%20fish%22%20OR%20%22Minnows%22%20OR%20%22Catfishes%22%20OR%20%22Salmons%22))

**Comment by kylie-m** [comment]
Update: I believe the issue is particular filters/facets, it may not be regions at all.  

I've got this similar Biocache query working now (ie species checklist download not blank) [https://biocache.ala.org.au/occurrence/search?q=cl10923%3A%22MORETON%20BAY%20REGIONAL%[…]group%3A%22Reptiles%22&fq=occurrence_status%3A%22PRESENT%22](https://biocache.ala.org.au/occurrence/search?q=cl10923%3A%22MORETON%20BAY%20REGIONAL%22&qualityProfile=ALA&fq=species_group%3A%22Reptiles%22&fq=occurrence_status%3A%22PRESENT%22#tab_mapView)

but when I add the additional filters in, it breaks (i.e. species checklist download is blank)
[https://biocache.ala.org.au/occurrence/search?q=cl10923%3A%22MORETON%20BAY%20REGIONAL%[…]A*&fq=occurrence_year%3A%5B*+TO+2023-12-31T23%3A59%3A59Z%5D](https://biocache.ala.org.au/occurrence/search?q=cl10923%3A%22MORETON%20BAY%20REGIONAL%22&qualityProfile=ALA&fq=(rank%3A%22species%22%20OR%20rank%3A%22subspecies%22)&fq=(species_subgroup%3A%22Lizards%2C%20Snakes%22%20OR%20species_subgroup%3A%22Tortoises%2C%20Turtles%2C%20Terrapins%22)&fq=geospatial_kosher%3A%22true%22&fq=occurrence_year%3A*&fq=occurrence_year%3A%5B*+TO+2023-12-31T23%3A59%3A59Z%5D#tab_mapView)

It seems to be narrowed down to both of the species subgroup facets 
1. 'Lizards and snakes'
https://biocache.ala.org.au/occurrence/search?q=*%3A*&qualityProfile=ALA&wkt=MULTIPOLYGON(((145.810546875%20-35.8044491119149%2C145.810546875%20-36.51405119943165%2C146.865234375%20-36.51405119943165%2C146.865234375%20-35.8044491119149%2C145.810546875%20-35.8044491119149)))&fq=species_subgroup%3A%22Lizards%2C%20Snakes%22#tab_mapView


2.  'Tortoises turtles and terrapins'
https://biocache.ala.org.au/occurrence/search?q=*%3A*&qualityProfile=ALA&wkt=MULTIPOLYGON(((145.810546875%20-35.8044491119149%2C145.810546875%20-36.51405119943165%2C146.865234375%20-36.51405119943165%2C146.865234375%20-35.8044491119149%2C145.810546875%20-35.8044491119149)))&fq=species_subgroup%3A%22Tortoises%2C%20Turtles%2C%20Terrapins%22#tab_mapView


Species checklist d/l is working for other species subgroup facts, and combinations of 2 , e.g.

**Comment by adam-collins** [comment]
Because the test environment does not have layer intersections at this time, please use this to test the species checklist download:
- prod, does not work, https://biocache.ala.org.au/occurrences/search?q=speciesSubgroup:(%22Killifishes%22%20OR%20%22Perch-like%20Fishes%22%20OR%20%22Scorpion%20Fishes,%20Sculpins%22%20OR%20%22Marine%20ray-finned%20fish%22%20OR%20%22Minnows%22%20OR%20%22Catfishes%22%20OR%20%22Salmons%22)
- test, fixed, https://biocache-test.ala.org.au/occurrences/search?q=speciesSubgroup:(%22Killifishes%22%20OR%20%22Perch-like%20Fishes%22%20OR%20%22Scorpion%20Fishes,%20Sculpins%22%20OR%20%22Marine%20ray-finned%20fish%22%20OR%20%22Minnows%22%20OR%20%22Catfishes%22%20OR%20%22Salmons%22)

**Comment by adam-collins** [comment]
fixed by this commit https://github.com/AtlasOfLivingAustralia/biocache-service/commit/4aa74e185b80fb4b3b1dea063e15de2b60f0078d

**Comment by kylie-m** [comment]
Thanks Adam! the test above worked for me too

**Comment by adam-collins** [comment]
deployed
